### PR TITLE
Fix for sendmany for Criptoreal

### PR DESCRIPTION
**Pull request by ExEric3**
error -1: json value is not a boolean as expected
Idea taken from https://bitcointalk.org/index.php?topic=2272607.2280

### CODE REVIEW

**Comment by tpruvot** [comment]
could you paste me the result of "help sendmany" from this wallet ?

**Comment by ExEric3** [comment]
At me locally worked after fix:
[2018-02-14 16:05:04] CRS sendtoaddress CSxYScnAqaJaoVn4ozPjzoGrPiux719DeX 142.56002876
[2018-02-14 16:05:04] payment done

Here is help: https://prnt.sc/iep4a6

**Comment by tpruvot** [comment]
yes, so the right "fix" is to uncheck the txmessage...

**Comment by AltMinerNet** [comment]
Uncheck txmessage should be sufficient.

**Comment by tpruvot** [comment]
https://github.com/tpruvot/yiimp/blob/next/web/yaamp/core/backend/payment.php#L195-L198

**Pull request closed without merging**
