### PR TITLE
Random fee option

### PR DESCRIPTION
**Pull request by phm87**
Needed for rare complex cases

### CODE REVIEW

**Comment by coolsd** [comment]
@phm87   Can you share the code for each coin's separate port implementation?

**Comment by phm87** [comment]
@coolsd  Sorry but I think that everything is already in github.

If you have some code to test, I'd be happy to test it.

I can help you but the code is already there and required reading to configure correctly the pool. Please read stratum code before any question on stratum as it is dangerous without understanding.

**Comment by coolsd** [comment]
@phm87 Thank you

**Comment by tpruvot** [comment]
no way, keep your random features for you :circus_tent:

**Comment by phm87** [comment]
@tpruvot  Ok thank you.

I will pay more attention to avoid to make pull requests related to particular cases (neraly impossible) that are useful for nearly no pools.

BTW, I made many random changes on testpools but there is no way to make pull request with that (too much risk). I'll pay more attention, thank you. ^^

**Pull request closed without merging**
