### PR TITLE
algo can now be passed as query page, either as a coma seperated list…

### PR DESCRIPTION
**Pull request by eLvErDe**
Hello,

The found_result page can be very useful for people scrapping pool results however it only returns the blocks found for the algorithm present in user's session (the last one he clicked on).

This PR add the possibility to pass it as a query param like ?algo=all or ?algo=x16s,x16r

Thanks,

### CODE REVIEW

**Comment by zhq1** [comment]
I tested, Last 50 Blocks is not showing after updating your file

**Comment by eLvErDe** [comment]
You have to request this specific page with the proper query param.
For example:
https://pool.ionik.fr/site/found_results?algo=all

Ask for refresh, sometime you get ancached page. It has been tested and reported working on two yiimp instances, including the one I linked here

**Comment by zhq1** [comment]
ERROR Operation timed out after 30001 milliseconds with 0 bytes received  
What is the reason for this situation?

**Comment by eLvErDe** [comment]
Can you please post full error message

**Comment by tpruvot** [comment]
not wanted

**Pull request closed without merging**
