### PR TITLE
enable asicboost

### PR DESCRIPTION
**Pull request by goodthebest**
changed from false to true,, to enable asicboost, not sure if it's correct approach?

### CODE REVIEW

**Comment by crackfoo** [comment]
did you test an S9 with this setting and asicboost? Seems too easy if this is all it took. :)

**Comment by phm87** [comment]
I think that some code should be added for version rolling related to asic boost:
"As to use Overt-AsicBoost, Slush Pool published a BIP (Bitcoin Improvement Proposal) to standardize Stratum Protocol Extension, in particular this BIP is a configuration of bits “version-rolling” in nVersion field of bitcoin block header.
https://github.com/slushpool/stratumprotocol/blob/master/stratum-extensions.mediawiki

To implement “version-rolling” it is necessary to extend stratum protocol simply because is backwards incompatible change. In fact, with the stratum protocol original version, miner couldn’t communicate different block version value to the server and a server couldn’t communicate safe bits for rolling to a miner."

https://medium.com/novamining/first-ever-block-mined-using-overt-asicboost-slush-pool-plans-stratum-protocol-extensions-as-a-bip-29dd319bb9e7


"{
...
"multi-version" : "1" 
}
To enable multi-version needs to be >1, the number being how many bits of the version number you're allowing it to modify for ASICBOOST. Enabling this will cause a new field in mining.submit which includes which version number it ended up using for the share solve, the pool server needs to be able to parse that and be able to validate it. The code for this is on github in the bit main account so don't take my word for it."

https://www.reddit.com/r/Bitcoin/comments/63yo27/some_circumstantial_evidence_supporting_the_claim/dfy5o65/

**Comment by CCGLLC-knc** [comment]
Just setting this value to true may be a start, but the stratum needs to handle the newish "mining.configure" protocol as well.

**Comment by HotSwapp** [comment]
Has anyone gotten this working?

**Comment by CCGLLC-knc** [comment]
The Zergpool folks have.

**Comment by GoldmanSocks** [comment]
bsod.pw also has asicboost on yiimp, many have this and this should be public shared as the home pool miners want this to help save power. 

Ref BIp 0310 = https://github.com/bitcoin/bips/blob/master/bip-0310.mediawiki

Changes to stratum client.cpp needed to enable the above ref commands.

**Comment by le2Ks** [comment]
Anyone been able to make this work? Will pay.

**Pull request closed without merging**
