### PR TITLE
Moved exchange keys and secrets to serverconfig

### PR DESCRIPTION
**Pull request by FireWalkerX**
instead of leaving the exchange keys and secrets sprinkled everywhere, ive put them into serverconfig file

### CODE REVIEW

**Comment by tpruvot** [comment]
yes, thanks but its the first thing i made there... but in two separate files to enhance a bit the security (public keys in main and a new one for secret keys)

I will publish soon my commits, i just need a bit more time to finish the mode without auto exchange...

**Comment by FireWalkerX** [comment]
so no autoexchange mode, will that be hardcoded, or selectable?

**Comment by tpruvot** [comment]
selectable (constant in config + stratum cflag for the moment), i made the last commits this night...

**Comment by tpruvot** [comment]
pushed my changes...

**Comment by tpruvot** [comment]
well... i will do a mix of our 2 commits... im on irc on #yiimp channel if required to discuss

**Comment by tpruvot** [comment]
done, i used your key constants, made that a bit fast on the beginning... ;) except BLEUTRADE vs BLUETRADE

**Comment by FireWalkerX** [comment]
lol minor spelling mistake there... i will pull your changes in later and whenever i do stuff that might be useful ill send you a note

**Comment by tpruvot** [comment]
I did not fully test the trade mode... i hope ive used config variables
everywhere. Feel free to report me the missing ones if you see some...
different ones for exchange and rental..

Are you running ffpool ?

2015-07-23 11:36 GMT+02:00 Fabian Olesen <notifications@github.com>:

**Comment by FireWalkerX** [comment]
no, im running a pool thats still in stealth mode :-p

**Pull request closed without merging**
