### PR TITLE
add yespower

### PR DESCRIPTION
**Pull request by mikasaukyou**

### CODE REVIEW

**Comment by ser9i0** [comment]
Hi, have you successfully tested this algorithm with any coin on Yiimp? I have pulled your branch in order to mine Bellcoin and I keep getting rejected messages with [cpuminer](https://github.com/bubasik/cpuminer-opt-yespower):

> Rejected 1698/1733 (98.0%), diff 5.56e-008, 735.25 H/s
> reject reason: Invalid share

Is it because you have implemented yespower 1.0 and cpuminer is using 0.9?
Thanks for your work!

**Comment by mikasaukyou** [comment]
Hello.
Sorry, this pull request is a mistake.
It was the source of the test.
https://pool.pecadol.xyz/
We have confirmed that Bellcoin is able to find out by operating above.
Yescrypt and Yespower will not work properly unless it is Diff 1 or higher. This is an original specification.
Right now, I am trying to change the source of stratum so that Diff can be 1 or less.

This is google translation.

**Comment by mikasaukyou** [comment]
Who does not know who is remodeling to make Diff less than 1?

**Comment by itwysgsl** [comment]
Hello @mikasaukyou, have you solved this issue?

**Pull request closed without merging**
