### PR TITLE
Add Nova trading

### PR DESCRIPTION
**Pull request by Tristian**
Added Nova trading code and upgraded Nova API to v2.
#103

### CODE REVIEW

**Comment by crackfoo** [comment]
I was away all weekend but I'll get to testing this when @tpruvot validates and merges.

Thanks!

**Comment by crackfoo** [comment]
@Tristian He's got one concern:

the api key is the params
in the $params var
which can be modified/returned from the function
a simple line can fix it
$params = array(); after the use

**Comment by crackfoo** [comment]
Thanks! I'll get to merging this today and testing

**Comment by Tristian** [comment]
@crackfoo #112

**Pull request merged**
